apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nstnr.com
  namespace: cert-manager
spec:
  secretName: nstnr.com
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - nstnr
  dnsNames:
    - 'nstnr.com'
    - '*.nstnr.com'

  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer