---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - ./helm