apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps/cert-manager/cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: cert-manager
