apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 5m
  path: ./flux/repositories
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg