apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 0.34.4
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
  install:
    createNamespace: true

