apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:EO09FoYgGJEtso0BCQwahKjN9Xn1oRJRUJXZdXbRz2Zravxk0ocsd33bh3hp4Tdne8Pe5SIo0KnaeOfvwTzYlg==,iv:7VIQURlDXygKDCKBknlH2xoEReabZUK35LgE2ZJtJ5s=,tag:GK1Gb1WJ65053mRVf3HLeQ==,type:str]
sops:
    lastmodified: "2025-10-15T19:20:13Z"
    mac: ENC[AES256_GCM,data:dXZgt5vH4dzzr6d/94OEjStvTGpFFY/QW+3RhDKMYVSZzoa9NSZB5K6O7BN5hcigdLgONB/PMF7216PwlEHBHC+tLywmL/GHafzJKp7XW5Z6jRHK8P7y78VSorvgsfVAn/6y/VfQBhHidhNw90IUluSIknwaUYiXmbUMIOt6AG4=,iv:qjj++oBmLJzxO2GcuQpwbFpUnXRXba70UrrBtUoMU/4=,tag:h8iOO0IYjXjWLF6JbAq9GQ==,type:str]
    pgp:
        - created_at: "2025-10-15T19:20:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dk7dKfW9EQIESAQdAq890/BXOi9YoXWOq1FL8cwToHFOrQNBDXkd5R7CV3X0w
            YYlaz0fAK/5G5UnYjMfhaznTMHJU5YsiitLSWB6eYBUFy7mETV4+VBFdDWiQoO4F
            1GgBCQIQBOGOse/xc5JmK0xJaOGO+2GBVs9diNuzjbdal4P5zTPIFuA/SceaasaO
            yDFGddEzZUxuu7kbtDiWKf7zutpUL8JwcOPhroFDcBPaContcc5qLHp3J4Xc7r64
            Plt8OOY6UQ87lg==
            =1aoB
            -----END PGP MESSAGE-----
          fp: 0838E38422232D44B96B6C7659A7C95E7A016E5A
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.11.0
